# Generated by Django 4.0.4 on 2022-05-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_camion_capacidaddeposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='alto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='ancho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='largo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='modelo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
