# Generated by Django 4.0.4 on 2022-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_cliente_lat_cliente_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
