# Generated by Django 4.0.4 on 2022-05-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
