# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_alter_extendeduser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'managed': True},
        ),
    ]
