# Generated by Django 4.0.4 on 2022-05-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_alter_extendeduser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
