# Generated by Django 4.0.4 on 2022-05-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_alter_extendeduser_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
