# Generated by Django 4.0.4 on 2022-05-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
