# Generated by Django 4.0.4 on 2022-05-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_alter_extendeduser_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
