# Generated by Django 4.0.4 on 2022-05-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0072_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='transportista',
        ),
    ]
