# Generated by Django 4.0.4 on 2022-05-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0076_extendeduser_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
