# Generated by Django 4.0.4 on 2022-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0084_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='movil',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
