# Generated by Django 4.0.4 on 2022-05-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0085_extendeduser_movil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={},
        ),
        migrations.AlterModelTable(
            name='extendeduser',
            table=None,
        ),
    ]
