# Generated by Django 4.0.4 on 2022-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0087_alter_extendeduser_options_alter_extendeduser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.CharField(max_length=45),
        ),
    ]
