# Generated by Django 4.0.4 on 2022-05-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0088_alter_cliente_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='camion',
        ),
        migrations.AddField(
            model_name='conductor',
            name='camiones',
            field=models.ManyToManyField(to='principal.camion'),
        ),
    ]
