# Generated by Django 4.0.4 on 2022-05-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0093_conductor_camiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='camiones',
        ),
    ]
