# Generated by Django 4.0.4 on 2022-05-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0094_remove_conductor_camiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorConduceCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.camion')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.conductor')),
            ],
        ),
    ]
