# Generated by Django 4.0.4 on 2022-05-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0095_conductorconducecamion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConductorConduceCamion',
        ),
    ]
