# Generated by Django 4.0.4 on 2022-05-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0097_conductorconducecamion_conductor_conducido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductorconducecamion',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='conductorconducecamion',
            unique_together={('camion', 'conductor', 'fecha')},
        ),
        migrations.AlterModelTable(
            name='conductorconducecamion',
            table='conductorconducecamion',
        ),
    ]
