# Generated by Django 4.0.4 on 2022-05-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0098_alter_conductorconducecamion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conductorconducecamion',
            table=None,
        ),
    ]
