# Generated by Django 4.0.4 on 2022-05-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0103_conductorconducecamion_conductor_conducido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='conducido',
        ),
        migrations.DeleteModel(
            name='ConductorConduceCamion',
        ),
    ]
