# Generated by Django 4.0.4 on 2022-05-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0105_extendeduser_transportista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='transportista',
        ),
    ]
