# Generated by Django 4.0.4 on 2022-05-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0152_extendeduser_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
