# Generated by Django 4.0.4 on 2022-05-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0156_extendeduser_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
