# Generated by Django 4.0.4 on 2022-05-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0158_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='test',
        ),
    ]
