# Generated by Django 4.0.4 on 2022-05-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0159_remove_extendeduser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.test'),
        ),
    ]
