# Generated by Django 4.0.4 on 2022-05-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0160_extendeduser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='test',
        ),
    ]
