# Generated by Django 4.0.4 on 2022-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0162_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
