# Generated by Django 4.0.4 on 2022-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0164_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
