# Generated by Django 4.0.4 on 2022-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0172_alter_conductor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
