# Generated by Django 4.0.4 on 2022-05-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0175_alter_conductor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='transportista',
        ),
    ]
