# Generated by Django 4.0.4 on 2022-05-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0176_remove_camion_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asigna',
        ),
    ]
