# Generated by Django 4.0.4 on 2022-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0177_delete_asigna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
