# Generated by Django 4.0.4 on 2022-05-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0178_alter_transportista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
