# Generated by Django 4.0.4 on 2022-05-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0185_remove_albaran_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albaran',
            name='cliente_dni',
        ),
    ]
