# Generated by Django 4.0.4 on 2022-05-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0186_remove_albaran_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercancia',
            name='albaran',
        ),
    ]
