# Generated by Django 4.0.4 on 2022-05-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0188_remove_mercancia_cliente_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
