# Generated by Django 4.0.4 on 2022-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0192_alter_albaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
