# Generated by Django 4.0.4 on 2022-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0193_alter_albaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
