# Generated by Django 4.0.4 on 2022-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0196_alter_camion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
