# Generated by Django 4.0.4 on 2022-05-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0199_albaran_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.estado'),
        ),
    ]
