# Generated by Django 4.0.4 on 2022-05-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0201_mercancia_albaran_mercancia_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='albaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.albaran'),
        ),
    ]
