# Generated by Django 4.0.4 on 2022-05-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0203_extendeduser_transportista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('transportista', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.transportista')),
                ('albaran', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.albaran')),
                ('camion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.camion')),
            ],
            options={
                'db_table': 'asigna',
                'managed': True,
                'unique_together': {('albaran', 'camion'), ('transportista', 'albaran')},
            },
        ),
    ]
