# Generated by Django 4.0.4 on 2022-05-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0204_ruta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ruta',
            table='ruta',
        ),
    ]
