# Generated by Django 4.0.4 on 2022-05-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0205_alter_ruta_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='movil',
        ),
    ]
