# Generated by Django 4.0.4 on 2022-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0207_conductorconducecamiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='conducido',
            field=models.ManyToManyField(through='principal.ConductorConduceCamiones', to='principal.camion'),
        ),
    ]
