# Generated by Django 4.0.4 on 2022-05-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0209_rename_conductorconducecamiones_conductoresconducencamiones_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conductoresconducencamiones',
            table='conductores_conducen_camiones',
        ),
    ]
