# Generated by Django 4.0.4 on 2022-05-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0211_alter_albaran_cliente_dni_alter_albaran_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='uid_firebase',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
