# Generated by Django 4.0.4 on 2022-06-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0213_conductor_email_conductor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='albaran',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.albaran'),
        ),
    ]
