# Generated by Django 4.0.4 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0215_alter_mercancia_albaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='fecharuta',
            field=models.DateField(db_column='fechaRuta', default='2000-01-01'),
        ),
    ]
