# Generated by Django 4.0.4 on 2022-06-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0217_alter_albaran_options_alter_camion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
