# Generated by Django 4.0.4 on 2022-06-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0221_extendeduser_transportista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={},
        ),
    ]
