# Generated by Django 4.0.4 on 2022-06-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0222_alter_extendeduser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.transportista'),
        ),
    ]
