# Generated by Django 4.0.4 on 2022-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0225_alter_camion_transportista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
