# Generated by Django 4.0.4 on 2022-06-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0226_alter_conductor_email_alter_conductor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoresconducencamiones',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.camion'),
        ),
        migrations.AlterField(
            model_name='conductoresconducencamiones',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.conductor'),
        ),
    ]
