# Generated by Django 4.0.4 on 2022-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0227_alter_conductoresconducencamiones_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
