# Generated by Django 4.0.4 on 2022-06-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0228_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='cliente_dni',
            field=models.ForeignKey(db_column='cliente_dni', on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.estado'),
        ),
    ]
