# Generated by Django 4.0.4 on 2022-06-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0229_alter_albaran_cliente_dni_alter_albaran_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.albaran'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.camion'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fecharuta',
            field=models.DateField(db_column='fechaRuta'),
        ),
    ]
