# Generated by Django 4.0.4 on 2022-06-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0230_alter_ruta_albaran_alter_ruta_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='cliente_dni',
            field=models.ForeignKey(db_column='cliente_dni', on_delete=django.db.models.deletion.CASCADE, to='principal.cliente'),
        ),
    ]
