# Generated by Django 4.0.4 on 2022-06-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0231_alter_mercancia_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='albaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.albaran'),
        ),
    ]
