# Generated by Django 4.0.4 on 2022-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0232_alter_mercancia_albaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='telefono',
            field=models.CharField(max_length=70),
        ),
    ]
