# Generated by Django 4.0.4 on 2022-06-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0234_alter_albaran_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='transportista',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='principal.transportista'),
        ),
    ]
