# Generated by Django 4.0.4 on 2022-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0235_alter_ruta_transportista'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('transportista', 'camion', 'albaran')},
        ),
    ]
