# Generated by Django 4.0.4 on 2022-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0240_alter_ruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
