# Generated by Django 4.0.4 on 2022-06-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0249_remove_ruta_id_alter_ruta_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='id',
            field=models.BigAutoField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='transportista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.transportista'),
        ),
    ]
