# Generated by Django 4.0.4 on 2022-06-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0251_remove_ruta_id_alter_ruta_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
