# Generated by Django 4.0.4 on 2022-06-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0252_delete_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecharuta', models.DateField(db_column='fechaRuta')),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.albaran')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.camion')),
                ('transportista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.transportista')),
            ],
            options={
                'db_table': 'ruta',
                'managed': True,
                'unique_together': {('transportista', 'camion', 'albaran')},
            },
        ),
    ]
