# Generated by Django 4.0.4 on 2022-06-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0256_ruta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conductoresconducencamiones',
            unique_together={('id', 'camion', 'conductor', 'fecha')},
        ),
    ]
