# Generated by Django 4.0.4 on 2022-06-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0257_alter_conductoresconducencamiones_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('transportista', 'camion', 'albaran', 'conductor', 'fecharuta')},
        ),
    ]
