# Generated by Django 4.0.4 on 2022-06-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0261_alter_ruta_albaran_alter_ruta_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.albaran'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.camion'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.conductor'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.transportista'),
        ),
    ]
